-- ============================================================
-- CẬP NHẬT NGÂN HÀNG CÂU HỎI ONBOARDING (54 CÂU MỚI)
-- Xóa câu cũ, insert 54 câu từ Google Sheets
-- Dùng chung cho cả onboarding test VÀ daily test
-- ============================================================

-- Bước 1: Reset session onboarding test cũ (tạo lại với câu hỏi mới)
DELETE FROM onboarding_test_questions
WHERE test_id IN (SELECT test_id FROM onboarding_tests);
DELETE FROM onboarding_tests;

-- Bước 2: Xóa câu hỏi onboarding cũ
DELETE FROM daily_questions WHERE bank_type = 'onboarding';

-- Bước 3: Insert 54 câu hỏi mới
INSERT INTO daily_questions (question_id, bank_type, question_text, option_a, option_b, option_c, option_d, correct_answer, is_active)
VALUES
  (gen_random_uuid(), 'onboarding', 'Toàn bộ công tác chấm công tại Công ty TNHH Doscom Holdings được thực hiện bằng hình thức nào?', 'Chấm công bằng vân tay đặt tại văn phòng.', 'Chấm công bằng định vị GPS qua ứng dụng Lark.', 'Chấm công bằng thẻ từ ra vào văn phòng.', 'Gửi email báo cáo ngày công cho quản lý trực tiếp hàng ngày.', 'B', true),
  (gen_random_uuid(), 'onboarding', 'Công ty TNHH Doscom Holdings quy định thế nào về hình thức làm việc online tại nhà?', 'Áp dụng cho toàn bộ nhân viên khi có lý do cá nhân chính đáng.', 'Chỉ áp dụng đối với bộ phận Chăm sóc khách hàng và Kỹ thuật.', 'Công ty không áp dụng hình thức làm việc online tại nhà.', 'Cho phép nhân viên làm việc online 01 ngày/tuần.', 'C', true),
  (gen_random_uuid(), 'onboarding', 'Khung giờ làm việc của ca hành chính từ Thứ 2 đến Thứ 7 hàng tuần được quy định như thế nào?', 'Từ 8h00 đến 17h00 hàng ngày (Thứ 7 về sớm 30 phút).', 'Từ 8h30 đến 17h30 hàng ngày (Thứ 7 về sớm 30 phút).', 'Từ 9h00 đến 18h00 hàng ngày (Thứ 7 về sớm 30 phút).', 'Từ 8h30 đến 18h00 hàng ngày (Thứ 7 về sớm 30 phút).', 'D', true),
  (gen_random_uuid(), 'onboarding', 'Trong một ngày làm việc bình thường, cán bộ nhân viên phải thực hiện chấm công trên ứng dụng Lark bao nhiêu lần?', '01 lần duy nhất vào đầu giờ sáng khi đến công ty.', '02 lần: Check in khi đến và Check out khi về.', '04 lần: Check in/out đầu giờ và Check in/out giữa ca nghỉ.', 'Không bắt buộc số lần chấm công, chỉ cần quản lý xác nhận.', 'B', true),
  (gen_random_uuid(), 'onboarding', 'Trường hợp không thể chấm công do lỗi phần mềm Lark hoặc các lý do khách quan khác, nhân viên cần phải làm gì?', 'Tự chấm công bù vào ngày làm việc tiếp theo.', 'Báo cáo bằng miệng cho Trưởng phòng/ban vào kỳ tính lương cuối tháng.', 'Báo ngay cho phòng Nhân sự để ghi nhận thời gian chấm công và khắc phục sự cố.', 'Chụp ảnh màn hình điện thoại tự lưu giữ và không cần báo ai.', 'C', true),
  (gen_random_uuid(), 'onboarding', 'Trong một tháng, nhân viên được xin phép đi muộn/về sớm lý do cá nhân tối đa bao nhiêu lần?', 'Đi muộn tối đa 3 lần, về sớm tối đa 2 lần.', 'Đi muộn/về sớm tối đa 3 lần.', 'Đi muộn tối đa 5 lần, về sớm tối đa 5 lần.', 'Đi muộn tối đa/về sớm tối đa 5 lần.', 'D', true),
  (gen_random_uuid(), 'onboarding', 'Quyền lợi ưu tiên về thời gian làm việc đối với lao động nữ nuôi con nhỏ dưới 12 tháng tuổi là gì?', 'Được nghỉ thêm 30 phút một ngày hưởng đủ lương.', 'Được nghỉ thêm 60 phút một ngày hưởng đủ lương (có thể chia ra sử dụng vào buổi trưa và buổi chiều) và phải báo với HCNS để theo dõi.', 'Được làm việc online tại nhà hoàn toàn cho đến khi con đủ 12 tháng tuổi.', 'Được về sớm trước 2 tiếng mỗi ngày và khấu trừ 10% lương cơ bản.', 'B', true),
  (gen_random_uuid(), 'onboarding', 'Nếu nhân viên phải đi giải quyết công việc công ty bên ngoài trước giờ làm việc sáng hoặc về muộn không thể quay lại công ty, họ phải thực hiện thủ tục gì?', 'Nhắn tin xin phép đồng nghiệp chung nhóm check-in hộ trên Lark.', 'Làm phiếu phê duyệt "Out off office" trong mục phê duyệt trên Lark và được Trưởng phòng/ban phê duyệt.', 'Gọi điện thoại trực tiếp xin phép Giám đốc và không cần làm đơn từ.', 'Viết biên bản giấy giải trình nộp lại cho phòng Hành chính Nhân sự sau 3 ngày.', 'B', true),
  (gen_random_uuid(), 'onboarding', 'Phiếu "Đơn xin đi muộn/về sớm" lý do cá nhân trường hợp về sớm phải được gửi phê duyệt trên Lark trước thời điểm về bao lâu?', 'Trước ít nhất 10 phút.', 'Trước ít nhất 15 phút.', 'Trước ít nhất 30 phút.', 'Trước ít nhất 1 tiếng.', 'B', true),
  (gen_random_uuid(), 'onboarding', 'Phiếu "Đơn xin đi muộn/về sớm" lý do cá nhân trường hợp đi muộn phải được gửi phê duyệt trên Lark trước thời điểm nào?', 'Trước 8h30 cùng ngày.', 'Trước 7h00 cùng ngày.', 'Trước 22h00 của ngày hôm trước.', 'Trước 12h00 trưa cùng ngày.', 'B', true),
  (gen_random_uuid(), 'onboarding', 'Khi muốn xin nghỉ phép từ 03 ngày trở lên, nhân viên phải gửi đơn xin nghỉ phép trước tối thiểu bao lâu?', 'Trước tối thiểu 03 ngày.', 'Trước tối thiểu 05 ngày.', 'Trước tối thiểu 01 tuần.', 'Trước tối thiểu 10 ngày.', 'C', true),
  (gen_random_uuid(), 'onboarding', 'Trường hợp xin nghỉ phép 02 ngày, nhân viên phải nộp đơn xin nghỉ trên Lark trước tối thiểu bao lâu?', 'Trước tối thiểu 01 ngày.', 'Trước tối thiểu 02 ngày.', 'Trước tối thiểu 03 ngày.', 'Trước tối thiểu 05 ngày.', 'C', true),
  (gen_random_uuid(), 'onboarding', 'Trường hợp xin nghỉ phép 01 ngày, nhân viên phải nộp đơn xin nghỉ trên Lark trước tối thiểu bao lâu?', 'Trước giờ bắt đầu làm việc ngày nghỉ 30 phút.', 'Trước tối thiểu 01 ngày.', 'Trước tối thiểu 02 ngày.', 'Phải nộp trước từ tuần trước.', 'B', true),
  (gen_random_uuid(), 'onboarding', 'Đối với trường hợp nghỉ đột xuất vì lý do bất khả kháng, nhân viên cần xử lý thế nào để chấm công hợp lệ?', 'Không cần thông báo, khi nào đi làm lại nộp đơn giải trình sau.', 'Thông báo ngay cho Trưởng bộ phận/người quản lý trực tiếp và HCNS để theo dõi chấm công, sau đó làm phiếu xin nghỉ bổ sung.', 'Nhắn tin cho đồng nghiệp cùng phòng nhờ chấm công hộ.', 'Gọi điện cho phòng Nhân sự xin phép và không cần làm phiếu trên Lark.', 'B', true),
  (gen_random_uuid(), 'onboarding', 'Trường hợp nghỉ không xin phép hoặc không được phê duyệt nghỉ (Nghỉ không lý do) 1/2 ngày bị phạt như thế nào?', 'Phạt 2 điểm vi phạm quy chế.', 'Phạt 1 ngày lương.', 'Phạt 2 ngày lương.', 'Không tính lương buổi nghỉ đó và phạt cảnh cáo.', 'B', true),
  (gen_random_uuid(), 'onboarding', 'Trường hợp nghỉ không xin phép hoặc không được phê duyệt nghỉ (Nghỉ không lý do) 01 ngày bị phạt thế nào?', 'Phạt trừ phép năm và phạt 1 ngày lương.', 'Phạt 2 ngày lương.', 'Phạt 3 ngày lương.', 'Đình chỉ công tác 03 ngày không hưởng lương.', 'B', true),
  (gen_random_uuid(), 'onboarding', 'Mức xử phạt đối với hành vi đi muộn/về sớm quá 5 lần trở lên, mỗi lần vi phạm phạt bao nhiêu điểm?', 'Phạt 0.5 điểm.', 'Phạt 1 điểm.', 'Phạt 1.5 điểm.', 'Phạt 2 điểm.', 'A', true),
  (gen_random_uuid(), 'onboarding', 'Theo nguyên tắc sử dụng tài sản, hành vi nào sau đây cán bộ nhân viên KHÔNG được tự ý thực hiện?', 'Trao đổi, cho mượn, sử dụng chéo giữa các cá nhân/bộ phận.', 'Di chuyển tài sản sang vị trí khác.', 'Cả A và B đều đúng.', 'Cài đặt các phần mềm được phục vụ cho công việc cá nhân.', 'C', true),
  (gen_random_uuid(), 'onboarding', 'Mọi nhu cầu điều chuyển, sử dụng chung tài sản của Công ty phải được phê duyệt bởi cơ quan/cá nhân nào?', 'Do các cá nhân/bộ phận tự thỏa thuận và ký biên bản ghi nhớ.', 'Phải được Phòng HCNS hoặc cấp quản lý trực tiếp phê duyệt.', 'Phải được Chủ tịch Công ty phê duyệt bằng văn bản chính thức.', 'Phải được Bộ phận Kế toán kiểm kê và đồng ý.', 'B', true),
  (gen_random_uuid(), 'onboarding', 'Số ngày phép hưởng nguyên lương tiêu chuẩn cho nhân viên chính thức là bao nhiêu ngày?', '0.5 ngày phép/tháng, tương đương 6 ngày phép/năm.', '01 ngày phép/tháng, tương đương 12 ngày phép/năm, thâm niên 5 năm + 01 ngày phép.', '1.5 ngày phép/tháng, tương đương 18 ngày phép/năm.', '02 ngày phép/tháng, tương đương 24 ngày phép/năm.', 'B', true),
  (gen_random_uuid(), 'onboarding', 'Chế độ nghỉ phép hưởng nguyên lương của Công ty áp dụng cho đối tượng nhân sự nào?', 'Toàn bộ cán bộ nhân viên đang làm việc, kể cả nhân sự thử việc và cộng tác viên.', 'Áp dụng đối với tất cả nhân sự học việc, thực tập sinh có thời gian làm việc trên 1 tháng.', 'Chỉ áp dụng đối với nhân viên đã ký Hợp đồng lao động (làm việc chính thức) tại Công ty.', 'Chỉ áp dụng cho các nhân sự cấp quản lý từ cấp Trưởng phòng trở lên.', 'C', true),
  (gen_random_uuid(), 'onboarding', 'Theo quy chế, nguyên tắc sử dụng ngày phép hằng tháng được quy định như thế nào?', 'Được cộng dồn tối đa 03 ngày phép sang các tháng tiếp theo trong cùng quý.', 'Ngày phép của tháng nào phải sử dụng hết tháng đó và không được tính cộng dồn vào các tháng tiếp theo.', 'Nhân viên có thể dồn toàn bộ 12 ngày phép để nghỉ một lần vào cuối năm.', 'Ngày phép chưa dùng hết sẽ được tự động quy đổi thành ngày nghỉ phép năm của năm tiếp theo.', 'B', true),
  (gen_random_uuid(), 'onboarding', 'Trường hợp nhân viên tự ý nghỉ làm mà không làm đơn xin phép (trừ các tình huống bất khả kháng đã được thông báo và duyệt trước 7h00) thì sẽ bị xử lý như thế nào?', 'Tính vào ngày nghỉ phép không hưởng lương thông thường.', 'Tính là ngày nghỉ không lý do và bị xử lý kỷ luật theo quy định Nghỉ không lý do của Công ty.', 'Chỉ bị nhắc nhở nội bộ và trừ 0.5 điểm phạt vào lương.', 'Sẽ bị sa thải trực tiếp mà không cần tiến hành các bước xử lý kỷ luật.', 'B', true),
  (gen_random_uuid(), 'onboarding', 'Trường hợp trễ deadline, cập nhật chậm tiến độ của Task sẽ chịu hình thức xử phạt là gì?', 'Trừ 1 điểm.', 'Nhắc nhở lần 1 qua tin nhắn nội bộ.', 'Lập biên bản cảnh cáo trước toàn bộ phòng ban.', 'Hạ bậc xếp loại thi đua tháng.', 'A', true),
  (gen_random_uuid(), 'onboarding', 'Ngày thành lập công ty TNHH Doscom Holdings là ngày bao nhiêu?', 'Ngày 1/6/2020.', 'Ngày 2/6/2020.', 'Ngày 1/6/2022.', 'Ngày 2/6/2021.', 'B', true),
  (gen_random_uuid(), 'onboarding', 'Theo quy định về cơ chế phạt, lỗi "Quên chấm công hằng ngày (check in/out)" ở lần thứ nhất bị trừ bao nhiêu điểm phạt?', 'Trừ 0.1 điểm phạt.', 'Trừ 0.25 điểm phạt.', 'Trừ 0.5 điểm phạt.', 'Không trừ điểm, chỉ nhắc nhở qua Lark.', 'B', true),
  (gen_random_uuid(), 'onboarding', 'Từ lần thứ 2 trở đi, mức điểm phạt đối với lỗi "Quên chấm công hằng ngày (check in/out)" được tính toán lũy tiến theo nguyên tắc nào?', 'Cố định trừ 0.5 điểm cho mỗi lần quên chấm công tiếp theo.', 'Điểm phạt bằng điểm phạt của lần 1 nhân đôi.', 'Điểm phạt được tính bằng: Điểm phạt gần nhất + 0.25.', 'Bị lập biên bản xử phạt trực tiếp trừ 1 ngày lương.', 'C', true),
  (gen_random_uuid(), 'onboarding', 'Hành vi "Làm việc riêng trong giờ làm, xem phim, chơi game,..." bị phát hiện sẽ bị trừ bao nhiêu điểm phạt vào lương?', 'Trừ 0.25 điểm phạt.', 'Trừ 0.5 điểm phạt.', 'Trừ 1 điểm phạt.', 'Trừ 2 điểm phạt.', 'B', true),
  (gen_random_uuid(), 'onboarding', 'Lỗi "Không thực hiện đúng quy trình làm việc theo quy định" sẽ bị áp dụng chế tài xử phạt là bao nhiêu điểm phạt?', 'Trừ 0.5 điểm phạt.', 'Trừ 1 điểm phạt.', 'Trừ 2 điểm phạt.', 'Trừ 3 điểm phạt.', 'C', true),
  (gen_random_uuid(), 'onboarding', 'Doscom quy định về điểm thưởng ra sao? Trường hợp nào nhân viên được cộng 0.5 điểm thưởng vào quỹ lương tuần?', 'Một tuần đi làm đầy đủ, đúng giờ (không đi muộn, về sớm).', 'Một tuần không mắc bất kỳ lỗi nào trong quy định.', 'Cả A và B đều đúng (mỗi trường hợp được cộng 0.5 điểm).', 'Đạt hiệu suất công việc xuất sắc nhất tuần.', 'C', true),
  (gen_random_uuid(), 'onboarding', 'Trong trường hợp ngày mùng 10 trùng vào ngày nghỉ hoặc ngày lễ theo quy định, lương của cán bộ nhân viên sẽ được chi trả vào thời điểm nào?', 'Sẽ được chi trả muộn hơn, vào ngày đầu tiên đi làm lại sau kỳ nghỉ.', 'Sẽ được chi trả vào ngày làm việc gần nhất trước hoặc sau ngày mùng 10 đó.', 'Mặc định chi trả đúng ngày mùng 10 thông qua hệ thống chuyển khoản tự động bất kể ngày lễ.', 'Sẽ được chuyển toàn bộ sang kỳ lương của tháng tiếp theo.', 'B', true),
  (gen_random_uuid(), 'onboarding', 'Theo Thông báo số 2705/2025/TB-DC, cán bộ nhân viên cần phản hồi tin nhắn trong vòng bao lâu kể từ khi nhận được?', 'Trong vòng 15 phút.', 'Trong vòng 30 phút.', 'Trong vòng 45 phút.', 'Trong ngày làm việc.', 'B', true),
  (gen_random_uuid(), 'onboarding', 'Nếu chưa thể trả lời chi tiết nội dung tin nhắn ngay lập tức, nhân viên cần xử lý như thế nào?', 'Chờ đến khi có đầy đủ thông tin chi tiết mới phản hồi.', 'Bỏ qua tin nhắn và trả lời sau.', 'Gửi tin nhắn xác nhận tạm thời.', 'Chỉ sử dụng emoji để kết thúc cuộc trò chuyện.', 'C', true),
  (gen_random_uuid(), 'onboarding', 'Khi được tag tên trực tiếp (@tên) trong các nhóm làm việc, hành vi nào sau đây đúng quy định?', 'Không cần phản hồi nếu không liên quan trực tiếp đến nhiệm vụ của mình.', 'Chỉ cần thả biểu tượng cảm xúc (emoji) là đủ.', 'Phản hồi trong vòng 30 phút hoặc thông báo cụ thể thời điểm sẽ phản hồi.', 'Chờ đến khi kết thúc ngày làm việc mới phản hồi một thể.', 'C', true),
  (gen_random_uuid(), 'onboarding', 'Tuyên ngôn văn hóa cải tiến chính thức của Doscom Holdings được quy định như thế nào?', '"Không ngừng sáng tạo, dẫn đầu công nghệ thông minh".', '"Cải tiến liên tục là chìa khóa của sự phát triển bền vững".', '"Mỗi ngày tại Doscom là một lần hệ thống, quy trình hoặc con người được cải tiến tốt hơn hôm qua."', '"Chủ động tìm kiếm giải pháp và tối ưu hóa chi phí vận hành".', 'C', true),
  (gen_random_uuid(), 'onboarding', 'Theo Thông báo số 1508/2025/TB-DC, tần suất tổ chức học tập định kỳ của Phòng Kinh doanh và Phòng Marketing lần lượt là bao nhiêu?', 'Phòng Kinh doanh: 02 tuần/lần; Phòng Marketing: 01 tuần/lần.', 'Phòng Kinh doanh: 01 tuần/lần; Phòng Marketing: 01 tuần/lần.', 'Phòng Kinh doanh: 01 tuần/lần; Phòng Marketing: 02 tuần/lần.', 'Phòng Kinh doanh: 01 tháng/lần; Phòng Marketing: 02 tuần/lần.', 'C', true),
  (gen_random_uuid(), 'onboarding', 'Trưởng phòng các bộ phận áp dụng Văn hóa Học tập có nhiệm vụ gửi thông báo lịch học cụ thể lên nhóm làm việc trước tối thiểu bao nhiêu ngày?', 'Trước tối thiểu 01 ngày.', 'Trước tối thiểu 02 ngày.', 'Trước tối thiểu 03 ngày.', 'Trước tối thiểu 05 ngày.', 'C', true),
  (gen_random_uuid(), 'onboarding', 'Công ty TNHH Doscom Holdings có bao nhiêu chi nhánh?', '1 chi nhánh ở HN.', '2 chi nhánh ở HN.', '1 chi nhánh ở HCM.', '1 chi nhánh ở HN và 1 chi nhánh ở HCM.', 'D', true),
  (gen_random_uuid(), 'onboarding', 'Tầm nhìn chiến lược của Doscom Holdings đến năm 2030 định vị công ty phát triển trở thành gì?', 'Hệ sinh thái công nghệ hàng đầu Việt Nam chuyên bán lẻ thiết bị camera.', 'Hệ sinh thái công nghệ tiêu dùng và giải pháp an tâm hàng đầu Việt Nam, dẫn đầu bằng AI, mở rộng bền vững ra Đông Nam Á và các thị trường quốc tế chọn lọc.', 'Công ty gia công phần mềm xuất khẩu lớn nhất khu vực Đông Nam Á.', 'Tập đoàn phân phối thiết bị gia dụng thông minh lớn thứ hai tại Việt Nam.', 'B', true),
  (gen_random_uuid(), 'onboarding', 'Hành vi nào dưới đây là HÀNH VI SAI đối với giá trị Chính trực và minh bạch?', 'Báo cáo đúng số liệu, chủ động báo lỗi, nói rõ rủi ro trước khi ra quyết định.', 'Không hứa điều công ty không chắc làm được; không che giấu phản hồi tiêu cực.', 'Sửa số liệu báo cáo; Che lỗi sản phẩm; Nói dối khách hàng; Hứa sai để chốt đơn; Đổ lỗi cho phòng ban khác; Im lặng khi thấy rủi ro; Báo cáo một nửa sự thật.', 'Truy nguyên nguyên nhân gốc thay vì đi tìm người để đổ lỗi.', 'C', true),
  (gen_random_uuid(), 'onboarding', 'Khẩu hiệu chính (Slogan) mang tính định hướng tối cao của Doscom Holdings là gì?', 'Công nghệ tin cậy, cuộc sống an tâm hằng ngày.', 'Tạo giá trị thật — Dẫn đầu bằng AI — Phụng sự bằng trách nhiệm.', 'Nói thật, làm thật, đo thật — Thành công bền vững.', 'Phát triển vì con người, cải tiến không ngừng nghỉ.', 'B', true),
  (gen_random_uuid(), 'onboarding', 'Đâu không phải là văn hóa đang tồn tại ở Doscom Holdings?', 'Văn hóa đọc sách.', 'Văn hóa học tập.', 'Văn hóa thể dục thể thao.', 'Văn hóa cải tiến.', 'C', true),
  (gen_random_uuid(), 'onboarding', 'Hành vi nào sau đây là hành vi ĐÚNG của Giá trị cốt lõi Con người trên hết tại Doscom?', 'Bỏ mặc nhân sự yếu tự bơi để họ tự sinh tự diệt và tự rèn luyện tính độc lập.', 'Góp ý thẳng thắn nhưng luôn giữ thái độ tôn trọng; đào tạo nhân sự trước khi phán xét.', 'Đánh giá năng lực của nhân sự chỉ dựa trên một lỗi duy nhất xảy ra trong tháng.', 'Dùng quyền lực cấp trên để ép nhân sự im lặng trong các cuộc họp đóng góp ý kiến.', 'B', true),
  (gen_random_uuid(), 'onboarding', 'Hành vi nào sau đây bị xếp vào nhóm hành vi SAI của Giá trị Con người trên hết?', 'Trao cơ hội cho những người có tiềm năng và sẵn sàng học hỏi cái mới.', 'Bảo vệ môi trường làm việc lành mạnh, rõ ràng, công bằng cho nhân viên.', 'Mắng chửi, hạ nhục, công kích cá nhân hoặc đánh giá con người chỉ qua một lỗi/một con số.', 'Ghi nhận nỗ lực đúng và kết quả thật của nhân sự dưới quyền.', 'C', true),
  (gen_random_uuid(), 'onboarding', 'Hành vi "Bao che người sai vì quan hệ cá nhân" thuộc nhóm hành vi nào tại Doscom Holdings?', 'Hành vi đúng vì thể hiện sự yêu thương, đùm bọc đồng nghiệp.', 'Hành vi sai của Giá trị cốt lõi Khách hàng an tâm.', 'Hành vi sai của Giá trị cốt lõi Con người trên hết.', 'Hành vi linh hoạt được khuyến khích để giữ sự hòa khí trong nội bộ.', 'C', true),
  (gen_random_uuid(), 'onboarding', 'Định nghĩa chuẩn xác nhất về tinh thần Tôn trọng con người tại Doscom Holdings là gì?', 'Là luôn đồng ý với mọi ý kiến của nhân sự để họ cảm thấy được tôn vinh.', '"Tôn trọng con người không có nghĩa là dễ dãi; tôn trọng là giúp họ phát triển, sống có trách nhiệm và tạo ra giá trị thật."', 'Là bỏ qua các lỗi quy trình nhỏ để giữ gìn mối quan hệ vui vẻ, thân thiết hằng ngày.', 'Là chỉ đánh giá cao những cá nhân mang lại doanh thu cao nhất, bỏ qua các chuẩn đạo đức khác.', 'B', true),
  (gen_random_uuid(), 'onboarding', 'Tư duy cốt lõi của Giá trị cốt lõi Khách hàng an tâm được phát biểu như thế nào?', 'Khách hàng là thượng đế, thượng đế luôn luôn đúng.', 'Doanh thu là tất cả, khách hàng hài lòng chỉ là điều kiện đủ.', '"Không có khách hàng an tâm, Doscom không có giá trị thật."', 'Tập trung giải quyết nhanh khiếu nại bằng cách đền bù tài chính vô điều kiện.', 'C', true),
  (gen_random_uuid(), 'onboarding', 'Hành vi nào sau đây là hành vi ĐÚNG của Giá trị Chính trực và minh bạch tại Doscom?', 'Làm đẹp số liệu báo cáo một chút để phòng ban đạt KPI và giữ uy tín chung.', '"Báo cáo đúng số liệu, chủ động báo lỗi, không hứa điều công ty không chắc làm được và truy nguyên nguyên nhân gốc thay vì tìm người đổ lỗi."', 'Im lặng khi thấy rủi ro rõ ràng của dự án để tránh gây hoang mang cho đội ngũ.', 'Báo cáo một nửa sự thật khó nghe để tránh làm Ban Giám đốc lo lắng quá mức.', 'B', true),
  (gen_random_uuid(), 'onboarding', 'Hành vi nào dưới đây bị coi là hành vi SAI nghiêm trọng của Giá trị Chính trực và minh bạch?', 'Truy nguyên nguyên nhân gốc rễ của lỗi vận hành hệ thống.', 'Nói rõ rủi ro với đối tác trước khi ký kết hợp đồng chính thức.', '"Sửa số liệu báo cáo, che lỗi sản phẩm, nói dối khách hàng hoặc báo cáo một nửa sự thật để né trách nhiệm."', 'Không che giấu các phản hồi tiêu cực từ người tiêu dùng thực tế.', 'C', true),
  (gen_random_uuid(), 'onboarding', 'Nhóm vi phạm nào tại Doscom Holdings có thể dẫn đến hình thức chế tài mạnh nhất là CHẤM DỨT HỢP TÁC ngay lập tức, bất kể cá nhân đó đang có doanh số hoặc thành tích cực tốt?', 'Làm giả số liệu báo cáo, che giấu lỗi nghiêm trọng, cố tình nói sai với khách hàng hoặc nội bộ.', 'Trễ deadline công việc lần đầu tiên trong năm và đã chủ động báo cáo sớm.', 'Tạm thời chưa thuần thục các kỹ năng sử dụng công cụ AI mới được đào tạo.', 'Đề xuất cải tiến quy trình làm việc cũ nhưng hiệu quả đạt được chưa như mong đợi.', 'A', true),
  (gen_random_uuid(), 'onboarding', 'Hành vi nào dưới đây bị xếp vào nhóm hành vi SAI của Giá trị Tốc độ có kỷ luật?', 'Báo sớm khi thấy dự án có nguy cơ trễ tiến độ để tìm giải pháp cứu vãn.', '"Họp nhiều nhưng không chốt, giao việc không rõ người phụ trách, làm nhanh nhưng không kiểm tra, trễ deadline mà không báo cáo."', 'Thiết lập tiêu chuẩn đầu ra rõ ràng cho từng nhiệm vụ của thành viên trong phòng ban.', 'Rút ra bài học kinh nghiệm và sửa đổi hệ thống vận hành sau mỗi thất bại của chiến dịch.', 'B', true),
  (gen_random_uuid(), 'onboarding', 'Chế tài nào sẽ được áp dụng tại Doscom khi một nhân sự trễ task không báo, làm ẩu gây lỗi hoặc lặp lại lỗi cũ nhiều lần?', 'Sẽ bị trừ điểm hiệu suất, cắt thưởng hoặc xem xét lại vị trí công việc.', 'Bắt buộc phải bồi thường bằng tiền mặt tương đương 100% giá trị của lỗi gây ra.', 'Không xử lý nếu nhân sự đưa ra lý do là phải làm nhanh để kịp tiến độ.', 'Leader sẽ làm thay cho nhân sự đó để đảm bảo tiến độ chung của toàn công ty.', 'A', true),
  (gen_random_uuid(), 'onboarding', 'Theo tiêu chuẩn văn hoá Trách nhiệm và không đổ lỗi, hành vi nào sau đây là ĐÚNG chuẩn mực khi có sự cố phát sinh?', '"Có lỗi thì chủ động báo sớm; có vấn đề thì tập trung xử lý; có thất bại thì rút ra bài học; không biến người khác thành lý do né tránh trách nhiệm."', 'Nhanh chóng tìm ra cá nhân hoặc phòng ban phối hợp kém để đổ lỗi nhằm bảo toàn uy tín cá nhân.', 'Im lặng tự giải quyết âm thầm để không làm ảnh hưởng đến đánh giá hiệu suất của bản thân.', 'Viết báo cáo thật dài để chứng minh rằng ngoại cảnh khách quan là nguyên nhân duy nhất gây ra thất bại.', 'A', true),
  (gen_random_uuid(), 'onboarding', 'Hành vi nào sau đây bị coi là vi phạm tiêu chuẩn Cải tiến và đổi mới tại Doscom?', 'Không bảo vệ cách cũ chỉ vì ngại thay đổi; không chờ hoàn hảo mới bắt đầu hành động.', 'Liên tục học tập các công cụ công nghệ mới để rút ngắn thời gian xử lý công việc.', '"Bảo thủ, khăng khăng giữ phương pháp làm việc cũ lạc hậu; lặp lại lỗi cũ hết lần này đến lần khác mà không sửa đổi hệ thống."', 'Chủ động đề xuất nâng cấp các quy trình vận hành lỗi thời của phòng ban.', 'C', true);
