// Theme catalog inspired by https://getdesign.md/
// Each theme defines a small set of CSS variables consumed by themes.css.

export interface Theme {
  id: string;
  name: string;
  category: string;
  description: string;
  mode: "dark" | "light";
  // Preview swatches shown in the picker
  swatches: [string, string, string, string];
}

export const THEME_CATEGORIES = [
  "Default",
  "Featured",
  "AI & LLM",
  "Developer Tools",
  "Backend & DevOps",
  "Productivity & SaaS",
  "Design & Creative",
  "Fintech & Crypto",
  "E-commerce",
  "Media & Consumer",
  "Automotive",
  "Other Platforms",
] as const;

export const THEMES: Theme[] = [
  // ─── Default ─────────────────────────────────────────────
  {
    id: "doscom",
    name: "DoScom Default",
    category: "Default",
    mode: "dark",
    description: "Mặc định — nền đen, nhấn xanh emerald",
    swatches: ["#09090B", "#0C0C0E", "#10B981", "#F4F4F5"],
  },

  // ─── Featured ────────────────────────────────────────────
  {
    id: "mastercard",
    name: "Mastercard",
    category: "Featured",
    mode: "light",
    description: "Warm cream canvas, orbital pill shapes, editorial warmth",
    swatches: ["#FAF6EE", "#FFFFFF", "#EB001B", "#1A1A1A"],
  },
  {
    id: "ibm",
    name: "IBM",
    category: "Featured",
    mode: "dark",
    description: "Carbon design system, structured blue palette",
    swatches: ["#161616", "#262626", "#0F62FE", "#F4F4F4"],
  },
  {
    id: "lamborghini",
    name: "Lamborghini",
    category: "Featured",
    mode: "dark",
    description: "True black surfaces, gold accents, dramatic uppercase",
    swatches: ["#000000", "#0A0A0A", "#D4AF37", "#FFFFFF"],
  },

  // ─── AI & LLM ────────────────────────────────────────────
  {
    id: "claude",
    name: "Claude",
    category: "AI & LLM",
    mode: "light",
    description: "Warm terracotta accent, clean editorial layout",
    swatches: ["#FAF7F2", "#FFFFFF", "#C96442", "#1A1A1A"],
  },
  {
    id: "cohere",
    name: "Cohere",
    category: "AI & LLM",
    mode: "dark",
    description: "Vibrant gradients, data-rich dashboard aesthetic",
    swatches: ["#0E0E14", "#1A1A24", "#FF7759", "#F0F0F5"],
  },
  {
    id: "elevenlabs",
    name: "ElevenLabs",
    category: "AI & LLM",
    mode: "dark",
    description: "Dark cinematic UI, audio-waveform aesthetics",
    swatches: ["#0A0A0A", "#141414", "#3B82F6", "#FAFAFA"],
  },
  {
    id: "mistral",
    name: "Mistral AI",
    category: "AI & LLM",
    mode: "light",
    description: "French-engineered minimalism, purple-toned",
    swatches: ["#FAFAFA", "#FFFFFF", "#FF7000", "#1A1A1A"],
  },
  {
    id: "minimax",
    name: "MiniMax",
    category: "AI & LLM",
    mode: "dark",
    description: "Bold dark interface with neon accents",
    swatches: ["#0B0B0F", "#15151B", "#00D9A0", "#F0F0F5"],
  },
  {
    id: "opencode",
    name: "OpenCode",
    category: "AI & LLM",
    mode: "dark",
    description: "Developer-centric dark theme",
    swatches: ["#0D0D0F", "#1A1A1F", "#FF9933", "#F0F0F0"],
  },
  {
    id: "togetherai",
    name: "Together AI",
    category: "AI & LLM",
    mode: "dark",
    description: "Technical, blueprint-style design",
    swatches: ["#0A0E1A", "#141B2D", "#5B8DEF", "#E8EDF5"],
  },
  {
    id: "xai",
    name: "xAI",
    category: "AI & LLM",
    mode: "dark",
    description: "Stark monochrome, futuristic minimalism",
    swatches: ["#000000", "#111111", "#FFFFFF", "#E0E0E0"],
  },

  // ─── Developer Tools ─────────────────────────────────────
  {
    id: "cursor",
    name: "Cursor",
    category: "Developer Tools",
    mode: "dark",
    description: "Sleek dark interface, gradient accents",
    swatches: ["#0F0F11", "#1A1A1E", "#7C3AED", "#F4F4F5"],
  },
  {
    id: "expo",
    name: "Expo",
    category: "Developer Tools",
    mode: "dark",
    description: "Dark theme, tight letter-spacing, code-centric",
    swatches: ["#0E0E12", "#1A1A22", "#4630EB", "#F0F0F8"],
  },
  {
    id: "linear",
    name: "Linear",
    category: "Developer Tools",
    mode: "dark",
    description: "Ultra-minimal, precise, purple accent",
    swatches: ["#08090A", "#16161A", "#5E6AD2", "#F0F0F4"],
  },
  {
    id: "raycast",
    name: "Raycast",
    category: "Developer Tools",
    mode: "dark",
    description: "Sleek dark chrome, vibrant gradient accents",
    swatches: ["#0E0E10", "#1C1C1F", "#FF6363", "#F2F2F4"],
  },
  {
    id: "warp",
    name: "Warp",
    category: "Developer Tools",
    mode: "dark",
    description: "Dark IDE-like interface, block-based command UI",
    swatches: ["#0C0C10", "#1A1A22", "#A78BFA", "#F0F0F5"],
  },

  // ─── Backend & DevOps ────────────────────────────────────
  {
    id: "clickhouse",
    name: "ClickHouse",
    category: "Backend & DevOps",
    mode: "light",
    description: "Yellow-accented, technical documentation style",
    swatches: ["#FFFFFF", "#FAFAFA", "#FFCC00", "#1A1A1A"],
  },
  {
    id: "hashicorp",
    name: "HashiCorp",
    category: "Backend & DevOps",
    mode: "dark",
    description: "Enterprise-clean, black and white",
    swatches: ["#0A0A0A", "#1C1C1C", "#7B42BC", "#FAFAFA"],
  },
  {
    id: "mongodb",
    name: "MongoDB",
    category: "Backend & DevOps",
    mode: "light",
    description: "Green leaf branding, developer documentation focus",
    swatches: ["#FFFFFF", "#F9FBFA", "#00ED64", "#001E2B"],
  },
  {
    id: "ollama",
    name: "Ollama",
    category: "Backend & DevOps",
    mode: "light",
    description: "Terminal-first, monochrome simplicity",
    swatches: ["#FFFFFF", "#F5F5F5", "#0A0A0A", "#1A1A1A"],
  },
  {
    id: "replicate",
    name: "Replicate",
    category: "Backend & DevOps",
    mode: "light",
    description: "Clean white canvas, code-forward",
    swatches: ["#FFFFFF", "#FAFAFA", "#000000", "#1A1A1A"],
  },
  {
    id: "sanity",
    name: "Sanity",
    category: "Backend & DevOps",
    mode: "light",
    description: "Red accent, content-first editorial layout",
    swatches: ["#FFFFFF", "#F7F7F7", "#F03E2F", "#101112"],
  },
  {
    id: "supabase",
    name: "Supabase",
    category: "Backend & DevOps",
    mode: "dark",
    description: "Dark emerald theme, code-first",
    swatches: ["#1C1C1C", "#262626", "#3ECF8E", "#EDEDED"],
  },

  // ─── Productivity & SaaS ─────────────────────────────────
  {
    id: "airtable",
    name: "Airtable",
    category: "Productivity & SaaS",
    mode: "light",
    description: "Colorful, friendly, structured data aesthetic",
    swatches: ["#FFFFFF", "#FBFBFC", "#FCB400", "#1A1A1A"],
  },
  {
    id: "calcom",
    name: "Cal.com",
    category: "Productivity & SaaS",
    mode: "dark",
    description: "Clean neutral UI, developer-oriented simplicity",
    swatches: ["#101010", "#1C1C1C", "#FFFFFF", "#E8E8E8"],
  },
  {
    id: "intercom",
    name: "Intercom",
    category: "Productivity & SaaS",
    mode: "light",
    description: "Friendly blue palette, conversational UI patterns",
    swatches: ["#FFFFFF", "#F4F7FA", "#286EFA", "#0E0F12"],
  },
  {
    id: "lovable",
    name: "Lovable",
    category: "Productivity & SaaS",
    mode: "light",
    description: "Playful gradients, friendly dev aesthetic",
    swatches: ["#FFFFFF", "#FAF7FF", "#FF66B2", "#1A1A1A"],
  },
  {
    id: "miro",
    name: "Miro",
    category: "Productivity & SaaS",
    mode: "light",
    description: "Bright yellow accent, infinite canvas aesthetic",
    swatches: ["#FFFFFF", "#FAFAF7", "#FFD02F", "#050038"],
  },
  {
    id: "notion",
    name: "Notion",
    category: "Productivity & SaaS",
    mode: "light",
    description: "Warm minimalism, serif headings, soft surfaces",
    swatches: ["#FFFFFF", "#F7F6F3", "#2F2F2F", "#37352F"],
  },
  {
    id: "zapier",
    name: "Zapier",
    category: "Productivity & SaaS",
    mode: "light",
    description: "Warm orange, friendly illustration-driven",
    swatches: ["#FFFFFF", "#FFF4ED", "#FF4F00", "#201515"],
  },

  // ─── Design & Creative ──────────────────────────────────
  {
    id: "figma",
    name: "Figma",
    category: "Design & Creative",
    mode: "dark",
    description: "Vibrant multi-color, playful yet professional",
    swatches: ["#0D0D0D", "#1E1E1E", "#A259FF", "#F0F0F0"],
  },
  {
    id: "framer",
    name: "Framer",
    category: "Design & Creative",
    mode: "dark",
    description: "Bold black and blue, motion-first, design-forward",
    swatches: ["#000000", "#111111", "#0099FF", "#FAFAFA"],
  },
  {
    id: "mintlify",
    name: "Mintlify",
    category: "Design & Creative",
    mode: "light",
    description: "Clean, green-accented, reading-optimized",
    swatches: ["#FFFFFF", "#FAFAFA", "#16A34A", "#0F172A"],
  },
  {
    id: "runway",
    name: "Runway",
    category: "Design & Creative",
    mode: "dark",
    description: "Cinematic dark UI, media-rich layout",
    swatches: ["#0A0A0A", "#161616", "#FFFFFF", "#E5E5E5"],
  },
  {
    id: "webflow",
    name: "Webflow",
    category: "Design & Creative",
    mode: "dark",
    description: "Blue-accented, polished marketing site aesthetic",
    swatches: ["#0F1014", "#1A1B23", "#4353FF", "#F0F0F8"],
  },

  // ─── Fintech & Crypto ───────────────────────────────────
  {
    id: "binance",
    name: "Binance",
    category: "Fintech & Crypto",
    mode: "dark",
    description: "Bold yellow accent on monochrome, trading urgency",
    swatches: ["#0B0E11", "#1E2329", "#F0B90B", "#EAECEF"],
  },
  {
    id: "coinbase",
    name: "Coinbase",
    category: "Fintech & Crypto",
    mode: "light",
    description: "Clean blue identity, trust-focused, institutional feel",
    swatches: ["#FFFFFF", "#F8FAFE", "#0052FF", "#0A0B0D"],
  },
  {
    id: "kraken",
    name: "Kraken",
    category: "Fintech & Crypto",
    mode: "dark",
    description: "Purple-accented dark UI, data-dense dashboards",
    swatches: ["#101218", "#1A1D26", "#7132F5", "#EAEAEC"],
  },
  {
    id: "revolut",
    name: "Revolut",
    category: "Fintech & Crypto",
    mode: "dark",
    description: "Sleek dark interface, gradient cards, fintech precision",
    swatches: ["#0B0F19", "#161B2A", "#0075EB", "#F0F2F8"],
  },
  {
    id: "wise",
    name: "Wise",
    category: "Fintech & Crypto",
    mode: "light",
    description: "Bright green accent, friendly and clear",
    swatches: ["#FFFFFF", "#F7F9FA", "#9FE870", "#163300"],
  },

  // ─── E-commerce ────────────────────────────────────────
  {
    id: "airbnb",
    name: "Airbnb",
    category: "E-commerce",
    mode: "light",
    description: "Warm coral accent, photography-driven, rounded UI",
    swatches: ["#FFFFFF", "#F7F7F7", "#FF385C", "#222222"],
  },
  {
    id: "nike",
    name: "Nike",
    category: "E-commerce",
    mode: "light",
    description: "Monochrome UI, massive uppercase type",
    swatches: ["#FFFFFF", "#F5F5F5", "#000000", "#111111"],
  },
  {
    id: "shopify",
    name: "Shopify",
    category: "E-commerce",
    mode: "dark",
    description: "Dark-first cinematic, neon green accent",
    swatches: ["#0A0A0A", "#161616", "#5DFA9F", "#F2F2F2"],
  },
  {
    id: "starbucks",
    name: "Starbucks",
    category: "E-commerce",
    mode: "light",
    description: "Four-tier green system, warm cream canvas",
    swatches: ["#F9F7F2", "#FFFFFF", "#006241", "#1E3932"],
  },

  // ─── Media & Consumer ──────────────────────────────────
  {
    id: "apple",
    name: "Apple",
    category: "Media & Consumer",
    mode: "light",
    description: "Premium white space, SF Pro, cinematic imagery",
    swatches: ["#FFFFFF", "#F5F5F7", "#0071E3", "#1D1D1F"],
  },
  {
    id: "meta",
    name: "Meta",
    category: "Media & Consumer",
    mode: "light",
    description: "Photography-first, binary surfaces, Meta Blue CTAs",
    swatches: ["#FFFFFF", "#F0F2F5", "#0866FF", "#050505"],
  },
  {
    id: "pinterest",
    name: "Pinterest",
    category: "Media & Consumer",
    mode: "light",
    description: "Red accent, masonry grid, image-first",
    swatches: ["#FFFFFF", "#FAFAFA", "#E60023", "#111111"],
  },
  {
    id: "playstation",
    name: "PlayStation",
    category: "Media & Consumer",
    mode: "dark",
    description: "Three-surface channel layout, cyan hover-scale",
    swatches: ["#0C0C12", "#1A1B26", "#00C8E0", "#F0F0F5"],
  },
  {
    id: "spotify",
    name: "Spotify",
    category: "Media & Consumer",
    mode: "dark",
    description: "Vibrant green on dark, bold type, album-art-driven",
    swatches: ["#121212", "#1A1A1A", "#1DB954", "#FFFFFF"],
  },
  {
    id: "verge",
    name: "The Verge",
    category: "Media & Consumer",
    mode: "dark",
    description: "Acid-mint and ultraviolet accents, rave-flyer story tiles",
    swatches: ["#0E0E10", "#1A1A20", "#A8FF60", "#F0F0F5"],
  },
  {
    id: "vodafone",
    name: "Vodafone",
    category: "Media & Consumer",
    mode: "light",
    description: "Monumental uppercase, Vodafone Red chapter bands",
    swatches: ["#FFFFFF", "#FAFAFA", "#E60000", "#0D0D0D"],
  },
  {
    id: "wired",
    name: "WIRED",
    category: "Media & Consumer",
    mode: "light",
    description: "Paper-white broadsheet density, ink-blue links",
    swatches: ["#FFFFFF", "#F7F7F7", "#1E3A8A", "#0A0A0A"],
  },

  // ─── Automotive ───────────────────────────────────────
  {
    id: "bmw",
    name: "BMW",
    category: "Automotive",
    mode: "dark",
    description: "Dark premium surfaces, precise German engineering",
    swatches: ["#0A0A0A", "#161616", "#1C69D4", "#F0F0F0"],
  },
  {
    id: "bugatti",
    name: "Bugatti",
    category: "Automotive",
    mode: "dark",
    description: "Cinema-black canvas, monochrome austerity",
    swatches: ["#000000", "#0F0F0F", "#0066B3", "#FAFAFA"],
  },
  {
    id: "ferrari",
    name: "Ferrari",
    category: "Automotive",
    mode: "dark",
    description: "Chiaroscuro editorial, Ferrari Red accents",
    swatches: ["#0B0B0B", "#161616", "#FF2800", "#FAFAFA"],
  },
  {
    id: "renault",
    name: "Renault",
    category: "Automotive",
    mode: "dark",
    description: "Vibrant aurora gradients, NouvelR typography, bold energy",
    swatches: ["#0E0E14", "#1A1A26", "#FFCC00", "#F0F0F5"],
  },
  {
    id: "spacex",
    name: "SpaceX",
    category: "Automotive",
    mode: "dark",
    description: "Stark black and white, full-bleed imagery",
    swatches: ["#000000", "#0D0D0D", "#FFFFFF", "#E5E5E5"],
  },
  {
    id: "tesla",
    name: "Tesla",
    category: "Automotive",
    mode: "dark",
    description: "Radical subtraction, full-viewport photography",
    swatches: ["#000000", "#0F0F0F", "#E31937", "#F4F4F4"],
  },

  // ─── Other Platforms ─────────────────────────────────
  {
    id: "composio",
    name: "Composio",
    category: "Other Platforms",
    mode: "dark",
    description: "Modern dark with colorful integration icons",
    swatches: ["#0E0E12", "#1A1A22", "#FF6B35", "#F0F0F5"],
  },
  {
    id: "posthog",
    name: "PostHog",
    category: "Other Platforms",
    mode: "dark",
    description: "Playful hedgehog branding, developer-friendly dark UI",
    swatches: ["#1D1D1D", "#2D2D2D", "#F9BD2B", "#EEEFE9"],
  },
  {
    id: "resend",
    name: "Resend",
    category: "Other Platforms",
    mode: "dark",
    description: "Minimal dark theme, monospace accents",
    swatches: ["#0A0A0A", "#161616", "#FFFFFF", "#F0F0F0"],
  },
  {
    id: "sentry",
    name: "Sentry",
    category: "Other Platforms",
    mode: "dark",
    description: "Dark dashboard, data-dense, pink-purple accent",
    swatches: ["#0F0A19", "#1B1525", "#E1567C", "#F0E8F5"],
  },
  {
    id: "stripe",
    name: "Stripe",
    category: "Other Platforms",
    mode: "light",
    description: "Signature purple gradients, weight-300 elegance",
    swatches: ["#FFFFFF", "#F6F9FC", "#635BFF", "#0A2540"],
  },
  {
    id: "superhuman",
    name: "Superhuman",
    category: "Other Platforms",
    mode: "dark",
    description: "Premium dark UI, keyboard-first, purple glow",
    swatches: ["#0A0A12", "#16162A", "#A78BFA", "#F0F0F8"],
  },
  {
    id: "uber",
    name: "Uber",
    category: "Other Platforms",
    mode: "dark",
    description: "Bold black and white, tight type, urban energy",
    swatches: ["#000000", "#1F1F1F", "#FFFFFF", "#EEEEEE"],
  },
  {
    id: "vercel",
    name: "Vercel",
    category: "Other Platforms",
    mode: "dark",
    description: "Black and white precision, Geist font",
    swatches: ["#000000", "#111111", "#FFFFFF", "#FAFAFA"],
  },
  {
    id: "voltagent",
    name: "VoltAgent",
    category: "Other Platforms",
    mode: "dark",
    description: "Void-black canvas, emerald accent, terminal-native",
    swatches: ["#050505", "#0F0F0F", "#10F2A1", "#EAEAEA"],
  },
];

export const DEFAULT_THEME_ID = "mistral";

export function getTheme(id: string): Theme {
  return THEMES.find((t) => t.id === id) ?? THEMES[0];
}
